<?php

namespace ClientBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllClients($clientname)
    {
        $qb = $this->createQueryBuilder('c');

        /**
         * recherche d'un client en particulier
         */
        if($clientname !== null) {
            $qb->andWhere('c.marque LIKE :clientname')
                ->setParameter('clientname', '%'.$clientname.'%');
        }

        $qb->orderBy('c.id', 'DESC');

        return $query = $qb->getQuery()->getResult();
    }
}
