<?php

namespace EvenementBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllEvenements($evenementname)
    {
        $qb = $this->createQueryBuilder('e');

        /**
         * recherche d'un evenement en particulier
         */
        if($evenementname !== null) {
            $qb->orWhere('e.nom LIKE :evenementname')
               ->orWhere('e.description LIKE :evenementname')
               ->setParameter('evenementname', '%'.$evenementname.'%');
        }

        $qb->orderBy('e.id', 'DESC');

        return $query = $qb->getQuery()->getResult();
    }
}
