<?php

namespace EvenementBundle\Repository;

/**
 * RassemblementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RassemblementRepository extends \Doctrine\ORM\EntityRepository
{
}
